character_names=["ben", "Gwen", "Kevin","sky", "dante"]
character_num=[1,2,4,7,2,9,0]
print(character_num)
print(character_names)
print("----------------")
character_names.extend(character_num)
print(character_names)
print("----------------")
character_names.append("Creed")
print(character_names)
character_names.insert(2,"Daniel")
print(character_names)
print("----------------")
character_names.remove("Gwen")
print(character_names)
print("----------------")
character_num.pop()
print(character_num)
print(character_names.index("Daniel"))
print("----------------")
print(character_num.count(2))
print("----------------")
print(character_num.sort())
character_num2=character_num.copy()
print(character_num2)

