print("next \n line")
print("print out \"things\" ")
print("----------------")
phrase="next level"
print( phrase + " is he")
print("----------------")
print(phrase.lower())
print(phrase.upper())
print("----------------")
print(phrase.isupper())
print(phrase.islower())
print("----------------")
print(len(phrase))
print("----------------")
print(phrase[0])
print(phrase[3])
print("----------------")
print(phrase.index("x"))
print(phrase.replace("next", "top"))

